### ISSUE TITLE
Get size via ioctl

### ISSUE THREAD

**Issue by flying-sheep** [SeanTater/pv#1]
In Python:

```py
import sys, os, fcntl, termios, array

fd = sys.stdin.fileno()
size_buf = array.array('i', [0])
fcntl.ioctl(fd, termios.FIONREAD, size_buf)
print(size_buf[0])
```

```console
$ du -b 'AUR Python.ipynb'
14457   AUR Python.ipynb
$ cat 'AUR Python.ipynb' | python pipe_size.py
14457
```

**Comment by SeanTater** [comment]
FIONREAD doesn't mean "how large is the file that is being piped to me", instead it means "how many bytes are available to be read in the input buffer".

There is some OS dependent logic to how large that buffer is; for OSX it's usually 16KB and for Linux usually 64KB. Try a larger file and you'll see it will be capped at 65536.
It might be interesting to show whether there is backpressure or not (e.g. whether the process before `pv` is slower or faster than the process after `pv`, which would change whether pv's output buffers are full). The issue with that is as long as we are using synchronous IO, we will just be descheduled when the buffer is full anyway so we won't be "awake" to see it full.

So at the moment I don't think we want to do this.
